/*
CREATED		17/09/2016
MODIFIED		18/09/2016
PROJECT		
MODEL			
COMPANY		
AUTHOR		
VERSION		
DATABASE		MS SQL 2005 
*/


CREATE TABLE [CONFIG]
(
	[TAIKHOAN] VARCHAR(50) NOT NULL,
	[MATKHAU] VARCHAR(50) NULL,
PRIMARY KEY ([TAIKHOAN])
) 
GO

CREATE TABLE [LOAISP]
(
	[MALOAISP] CHAR(2) NOT NULL,
	[TENLOAISP] NVARCHAR(5) NULL, UNIQUE ([TENLOAISP]),
PRIMARY KEY ([MALOAISP])
) 
GO

CREATE TABLE [NHACUNGCAP]
(
	[MANCC] INTEGER IDENTITY(1,1) NOT NULL,
	[TENNCC] NVARCHAR(50) NULL,
	[DIACHINCC] NVARCHAR(MAX) NULL,
	[SODTNCC] VARCHAR(11) NULL,
	[EMAILNCC] VARCHAR(50) NULL,
PRIMARY KEY ([MANCC])
) 
GO

CREATE TABLE [DONNHAPHANG]
(
	[MANH] INTEGER IDENTITY(1,1) NOT NULL,
	[MANCC] INTEGER NOT NULL,
	[NGAYNHAP] DATETIME NULL,
	[TONGTIENNHAP] NUMERIC(12,0) NULL CHECK (TONGTIENNHAP >= 0),
PRIMARY KEY ([MANH])
) 
GO

CREATE TABLE [SANPHAM]
(
	[MASP] INTEGER IDENTITY(1,1) NOT NULL,
	[TENSP] NVARCHAR(50) NULL,
	[SOLUONGTON] INTEGER NULL CHECK (SOLUONGTON >= 0),
	[GIABAN] NUMERIC(12,0) NULL CHECK (GIABAN > 0),
	[MALOAISP] CHAR(2) NOT NULL,
	[MATH] VARCHAR(5) NOT NULL,
	[MAPC] INTEGER NOT NULL,
PRIMARY KEY ([MASP])
) 
GO

CREATE TABLE [THUONGHIEU]
(
	[MATH] VARCHAR(5) NOT NULL,
	[TENTH] NVARCHAR(50) NULL, UNIQUE ([TENTH]),
PRIMARY KEY ([MATH])
) 
GO

CREATE TABLE [PHONGCACH]
(
	[MAPC] INTEGER IDENTITY(1,1) NOT NULL,
	[TENPC] NVARCHAR(50) NULL, UNIQUE ([TENPC]),
PRIMARY KEY ([MAPC])
) 
GO

CREATE TABLE [SIZE]
(
	[MASIZE] INTEGER IDENTITY(1,1) NOT NULL,
	[TENSIZE] NVARCHAR(10) NULL, UNIQUE ([TENSIZE]),
PRIMARY KEY ([MASIZE])
) 
GO

CREATE TABLE [HINHTHUCTHANHTOAN]
(
	[MAHTTT] INTEGER IDENTITY(1,1) NOT NULL,
	[TENHTTT] NVARCHAR(50) NULL,
PRIMARY KEY ([MAHTTT])
) 
GO

CREATE TABLE [HINHTHUCVANCHUYEN]
(
	[MAHTVC] INTEGER IDENTITY(1,1) NOT NULL,
	[TENHTVC] NVARCHAR(50) NULL, UNIQUE ([TENHTVC]),
PRIMARY KEY ([MAHTVC])
) 
GO

CREATE TABLE [KHACHHANG]
(
	[USER] VARCHAR(20) NOT NULL,
	[MATKHAU] VARCHAR(20) NOT NULL,
	[HOTENKH] NVARCHAR(50) NULL,
	[EMAILKH] VARCHAR(50) NULL,
	[DIACHIKH] NVARCHAR(MAX) NULL,
	[SODTKH] VARCHAR(11) NULL,
PRIMARY KEY ([USER])
) 
GO

CREATE TABLE [DONDATHANG]
(
	[MADDH] INTEGER IDENTITY(1,1) NOT NULL,
	[NGAYMUA] DATETIME NULL,
	[GHICHU] NVARCHAR(MAX) NULL,
	[TONGTIENDAT] NUMERIC(12,0) NULL CHECK (TONGTIENDAT >= 0),
	[MAHTTT] INTEGER NOT NULL,
	[TRANGTHAITHANHTOAN] BIT NULL,
	[MAHTVC] INTEGER NOT NULL,
	[TRANGTHAIGIAOHANG] BIT NULL,
	[IDNN] INTEGER NOT NULL,
PRIMARY KEY ([MADDH])
) 
GO

CREATE TABLE [CT_DATHANG]
(
	[MASP] INTEGER NOT NULL,
	[MADDH] INTEGER NOT NULL,
	[SOLUONGDAT] INTEGER NULL CHECK (SOLUONGDAT > 0),
PRIMARY KEY ([MASP],[MADDH])
) 
GO

CREATE TABLE [CT_NHAPHANG]
(
	[MANH] INTEGER NOT NULL,
	[MASP] INTEGER NOT NULL,
	[GIANHAP] NUMERIC(12,0) NULL CHECK (GIANHAP > 0),
	[SOLUONGNHAP] INTEGER NULL CHECK (SOLUONGNHAP > 0),
PRIMARY KEY ([MANH],[MASP])
) 
GO

CREATE TABLE [SIZE_SANPHAM]
(
	[MASP] INTEGER NOT NULL,
	[MASIZE] INTEGER NOT NULL,
PRIMARY KEY ([MASP],[MASIZE])
) 
GO

CREATE TABLE [HINHANH]
(
	[MAHINH] INTEGER IDENTITY(1,1) NOT NULL,
	[URLHINH] VARCHAR(MAX) NULL,
	[MASP] INTEGER NOT NULL,
PRIMARY KEY ([MAHINH])
) 
GO

CREATE TABLE [MAU]
(
	[MAMAU] INTEGER NOT NULL,
	[TENMAU] NVARCHAR(50) NULL, UNIQUE ([TENMAU]),
	[MASOMAU] VARCHAR(10) NULL,
PRIMARY KEY ([MAMAU])
) 
GO

CREATE TABLE [MAUSAC_SANPHAM]
(
	[MAMAU] INTEGER NOT NULL,
	[MASP] INTEGER NOT NULL,
PRIMARY KEY ([MAMAU],[MASP])
) 
GO

CREATE TABLE [TT_NGUOINHAN]
(
	[IDNN] INTEGER IDENTITY(1,1) NOT NULL,
	[USER] VARCHAR(20) NOT NULL,
	[TENNN] NVARCHAR(50) NULL,
	[DIACHINN] NVARCHAR(MAX) NULL,
	[SODTNN] NCHAR(11) NULL,
PRIMARY KEY ([IDNN])
) 
GO


ALTER TABLE [SANPHAM] ADD  FOREIGN KEY([MALOAISP]) REFERENCES [LOAISP] ([MALOAISP])  ON UPDATE NO ACTION ON DELETE NO ACTION 
GO
ALTER TABLE [DONNHAPHANG] ADD  FOREIGN KEY([MANCC]) REFERENCES [NHACUNGCAP] ([MANCC])  ON UPDATE NO ACTION ON DELETE NO ACTION 
GO
ALTER TABLE [CT_NHAPHANG] ADD  FOREIGN KEY([MANH]) REFERENCES [DONNHAPHANG] ([MANH])  ON UPDATE NO ACTION ON DELETE NO ACTION 
GO
ALTER TABLE [CT_DATHANG] ADD  FOREIGN KEY([MASP]) REFERENCES [SANPHAM] ([MASP])  ON UPDATE NO ACTION ON DELETE NO ACTION 
GO
ALTER TABLE [CT_NHAPHANG] ADD  FOREIGN KEY([MASP]) REFERENCES [SANPHAM] ([MASP])  ON UPDATE NO ACTION ON DELETE NO ACTION 
GO
ALTER TABLE [SIZE_SANPHAM] ADD  FOREIGN KEY([MASP]) REFERENCES [SANPHAM] ([MASP])  ON UPDATE NO ACTION ON DELETE NO ACTION 
GO
ALTER TABLE [HINHANH] ADD  FOREIGN KEY([MASP]) REFERENCES [SANPHAM] ([MASP])  ON UPDATE NO ACTION ON DELETE NO ACTION 
GO
ALTER TABLE [MAUSAC_SANPHAM] ADD  FOREIGN KEY([MASP]) REFERENCES [SANPHAM] ([MASP])  ON UPDATE NO ACTION ON DELETE NO ACTION 
GO
ALTER TABLE [SANPHAM] ADD  FOREIGN KEY([MATH]) REFERENCES [THUONGHIEU] ([MATH])  ON UPDATE NO ACTION ON DELETE NO ACTION 
GO
ALTER TABLE [SANPHAM] ADD  FOREIGN KEY([MAPC]) REFERENCES [PHONGCACH] ([MAPC])  ON UPDATE NO ACTION ON DELETE NO ACTION 
GO
ALTER TABLE [SIZE_SANPHAM] ADD  FOREIGN KEY([MASIZE]) REFERENCES [SIZE] ([MASIZE])  ON UPDATE NO ACTION ON DELETE NO ACTION 
GO
ALTER TABLE [DONDATHANG] ADD  FOREIGN KEY([MAHTTT]) REFERENCES [HINHTHUCTHANHTOAN] ([MAHTTT])  ON UPDATE NO ACTION ON DELETE NO ACTION 
GO
ALTER TABLE [DONDATHANG] ADD  FOREIGN KEY([MAHTVC]) REFERENCES [HINHTHUCVANCHUYEN] ([MAHTVC])  ON UPDATE NO ACTION ON DELETE NO ACTION 
GO
ALTER TABLE [TT_NGUOINHAN] ADD  FOREIGN KEY([USER]) REFERENCES [KHACHHANG] ([USER])  ON UPDATE NO ACTION ON DELETE NO ACTION 
GO
ALTER TABLE [CT_DATHANG] ADD  FOREIGN KEY([MADDH]) REFERENCES [DONDATHANG] ([MADDH])  ON UPDATE NO ACTION ON DELETE NO ACTION 
GO
ALTER TABLE [MAUSAC_SANPHAM] ADD  FOREIGN KEY([MAMAU]) REFERENCES [MAU] ([MAMAU])  ON UPDATE NO ACTION ON DELETE NO ACTION 
GO
ALTER TABLE [DONDATHANG] ADD  FOREIGN KEY([IDNN]) REFERENCES [TT_NGUOINHAN] ([IDNN])  ON UPDATE NO ACTION ON DELETE NO ACTION 
GO


SET QUOTED_IDENTIFIER ON
GO


SET QUOTED_IDENTIFIER OFF
GO


